### ISSUE TITLE
Update the nexus-python-sdk test files to be in sync with the nexus-python-sdk implementation

### ISSUE THREAD

**Issue by annakristinkaufmann** [BlueBrain/nexus-python-sdk#51]
This is feedback provided after a first usage of the nexus-python-sdk and its documentation to perform basic operations in a Nexus V1 deployment.

The test cases provided in the `tests` directory are currently out of sync with the nexus-python-sdk implementation, e.g.

* `test_organization.py` contains a `name="My Org"` in Line 38, while this is no longer a supported argument
* `test_resource.py` contains a `id="the-fancy-id-i-absolutely-need"` in Line 60, while this should be `resource_id`

**Comment by hygt** [comment]
Fixed in #82
