### ISSUE TITLE
Method create_link should create 502 error for nonexistent source

### ISSUE THREAD

**Issue by alex4200** [BlueBrain/nexus-python-sdk#66]
### Expected behavior

When I invoke the method `create_link` with a source path to a nonexistent file, the command should fail with a 502 error (henry). 

Should this also the behavior for e.g. an empty destination filepath?

### Actual Behavior (please include screenshot if possible)

What happens is a 500 error `requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://dev.nexus.ocp.bbp.epfl.ch/v1/files/gpfs_tests/gpfs_tests`.

### Steps to reproduce the problem

```
nexus.files.create_link(org_label=config.ORG, project_label=config.PROJECT,
              filename=filename, filepath=filepath, media_type='application/octet-stream')
```

with `filepath` pointing to a nonexistent file. 

### Optional infrastructural data (user, platform, browser, environment, ...)

http://dev.nexus.ocp.bbp.epfl.ch, nexus-python-sdk 496830e649da3293c01c326cb1e510a79265a29d

**Comment by umbreak** [comment]
When you specify a source path that does not exists, the status code should be `404 Not Found`. Right now the API returns `500 Server Error`. I'm fixing that
