### ISSUE TITLE
Unable to upload empty file to gpfs nexus storage via python SDK.

### ISSUE THREAD

**Issue by alex4200** [BlueBrain/nexus-python-sdk#67]
### Expected behavior

Able to upload an empty file into gpfs nexus storage. (according to @hygt ). 

### Actual Behavior (please include screenshot if possible)

When trying to upload an empty file, I get a 500 Server Error

### Steps to reproduce the problem

`nexus.files.create(org_label=config.ORG, project_label=config.PROJECT, filepath=file_path)`
where `filepath` points to an existing, but empty file.

### Optional infrastructural data (user, platform, browser, environment, ...)

http://dev.nexus.ocp.bbp.epfl.ch/v1, nexus-python-sdk commit 496830e649da3293c01c326cb1e510a79265a29d

**Comment by umbreak** [comment]
When you specify a source path that does not exists, the status code should be `404 Not Found`. Right now the API returns `500 Server Error`. I'm fixing that
