### ISSUE TITLE
Able to upload data as different user

### ISSUE THREAD

**Issue by alex4200** [BlueBrain/nexus-python-sdk#68]
### Expected behavior

Without giving permission to a different user, that different user is not able to access a user's project or upload data. 

### Actual Behavior (please include screenshot if possible)

Different user can access primary user's data ad upload data. 

### Steps to reproduce the problem

1. Log in to the web application with a different github user account. 
2. Set the token of that user
3. Upload data into the primary user's project

### Optional infrastructural data (user, platform, browser, environment, ...)

http://dev.nexus.ocp.bbp.epfl.ch/v1, nexus-python-sdk commit 496830e

**Comment by bogdanromanx** [comment]
This is a configuration property of the environment, not a bug in the software. ACLs are considered when the API is invoked, having inappropriate ACLs is a matter of env configuration rather than an incorrect system behaviour.

**Comment by alex4200** [comment]
@bogdanromanx So how can the access from a different user be tested?

**Comment by umbreak** [comment]
You can try that with anonymous (No Authentorization header).
In practice is the same.
