### ISSUE TITLE
mediaType in files.create_link does not have an effect

### ISSUE THREAD

**Issue by alex4200** [BlueBrain/nexus-python-sdk#69]
When using the method `files.create_link` you need to set a 'media type'. However this value does not seem to be used, you can specify nonsense and the method still works. 

Can this parameter removed, or will it have a meaning in the future?

**Comment by umbreak** [comment]
You cannot put anything in the mediaType field. If you would put

```
{
...
   "mediaType": "This is not a media type"
...
}
```

it will fail with the following message:
```
{
    "@context": "https://bluebrain.github.io/nexus/contexts/error.json",
    "@type": "InvalidResourceFormat",
    "details": "The provided payload could not be mapped to the targeted resource due to 'Expected a media type, but found otherwise'",
    "reason": "Resource 'http://dev.nexus.ocp.bbp.epfl.ch/v1/resources/gpfs_tests/gpfs_tests/_/myfile5' has an invalid format.",
    "ref": "http://dev.nexus.ocp.bbp.epfl.ch/v1/resources/gpfs_tests/gpfs_tests/_/myfile5"
}
```

mediatype is a metadata field which will be stored in the ElasticSearch and Blazegraph indices. This is part of the provenance information which can be used for:
- Applications, to know which is the media-type associated to an attachment
- Search, to filter every attachment with a certain media-type

**Comment by alex4200** [comment]
@umbreak When I use `media_type="This is not a media type"` in the API call, I get a 400 error (Bad request). 

Also, when I use `media_type="aa/bb"` the command finishes correctly, i.e. the file is being registered.

**Comment by umbreak** [comment]
Ok. So that's the expected behaviour. I will close the issue.

Feel free to re-open it if you feel there is something else to be fixed.
