### ISSUE TITLE
Downloading data: curl: (18) transfer closed with outstanding read data remaining

### ISSUE THREAD

**Issue by alex4200** [BlueBrain/nexus-python-sdk#71]
### Expected behavior

To be able to download a 100 MB file from nexus.
According to @umbreak the service is configured to handle 10GB files

`akka.http.server.parsing.max-content-length = 10g`

### Actual Behavior (please include screenshot if possible)

```
curl -XGET  -H "Authorization: Bearer ${TOKEN}"  "http://dev.nexus.ocp.bbp.epfl.ch/v1/files/gpfs_tests/gpfs_tests/06067b36-bd06-48ad-bf43-de2363e1193f"  -o data.dat
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 8044k    0 8044k    0     0  21.6M      0 --:--:-- --:--:-- --:--:-- 21.6M
curl: (18) transfer closed with outstanding read data remaining
```

### Steps to reproduce the problem

1. Upload a 100MB data file into nexus
2. Try to download it via curl

**Comment by umbreak** [comment]
This is now fixed: https://github.com/BlueBrain/nexus/issues/672
