### ISSUE TITLE
remove the need from copy-pasting the token from a web GUI

### ISSUE THREAD

**Issue by jdcourcol** [BlueBrain/nexus-python-sdk#72]
As I understand, in order to login with the sdk, we have to open in addition a web GUI, copy paste a token, and paste it to an environment variable.

I would prefer a standard workflow, where the user is being asked for his password , and that is it ,  as it is done for HBP services for instances.

**Comment by jdcourcol** [comment]
cc: @bogdanromanx

**Comment by hygt** [comment]
This was implemented in the CLI BlueBrain/nexus-cli#34
