### ISSUE TITLE
Creating resource with schema_id at None

### ISSUE THREAD

**Issue by jonathanlurie** [BlueBrain/nexus-python-sdk#83]
At this line: 
https://github.com/BlueBrain/nexus-python-sdk/blob/cfdd5393ab247ebf47e42eaf3133a3595c35c1d5/nexussdk/resources.py#L89

we can see that if the schema is explicitly set to None when creating a new resource, the schema_id value will be internally set to `resource`, while it should be set to `_` (underscore). I think this is a remnant of how it was done before `_` was a thing.

**Comment by hygt** [comment]
Fixed in #82
