### ISSUE TITLE
Use requests 'params' in http module

### ISSUE THREAD

**Issue by pafonta** [BlueBrain/nexus-python-sdk#9]
We should use ['params' in requests](http://docs.python-requests.org/en/master/user/quickstart/#passing-parameters-in-urls) in the http module. It would remove a lot of boilerplate because it handles the URL building **and** the URL encoding of the parameters.

**Comment by jonathanlurie** [comment]
Sounds good, we should test that!

**Comment by pafonta** [comment]
Done. However, not all the code used it at the moment.
